const data = [
  {
    id: 1,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 2,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 3,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 4,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 5,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 6,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 7,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 8,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 9,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 10,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 11,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 12,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 13,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 14,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 15,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 16,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 17,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 18,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 19,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 20,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 21,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 22,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 23,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 24,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
  {
    id: 25,
    name: "Ahmed",
    tokenAddress: "Token Address",
    devBuy: "Dev Buy",
    sol: "1 SOL",
    mcap: "$4,119.478",
    condingCurve: "75%",
    timeAgo: "2 Sec Ago",
  },
];

export default data;
